name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run Installs & Project Build
      run: |
        npm ci
        npm run build

    - name: Run Unit & Integration Tests
      run: npm run test

    - name: Run e2e Tests
      uses: cypress-io/github-action@v2
      with:
        record: false
        start: npm run start
        wait-on: 'http://localhost:4200'